language: r
os: linux
dist: bionic
cache:
  - packages
  - $HOME/.ccache
latex: false

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

r_packages:
  - caret

env:
  global:
  - MAKEFLAGS="-j 2"

deploy.skip_cleanup: true

jobs:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  fast_finish: true
